export const defaultConfig = {
  header: {
    backgroundImage: "",
    title: "",
    subtitle: "",
    buttonText: "",
  },
  section2: {
    image: "",
    title: "",
    description: "",
    buttonText: "",
  },
  section3: {
    title: "",
    description: "",
  },
  news: {
    image1: "",
    title1: "",
    date1: "",
    image2: "",
    title2: "",
    date2: "",
    image3: "",
    title3: "",
    date3: "",
  },
  section5: {
    image: "",
    title: "",
    description: "",
    buttonText: "",
  },
  section6: {
    title: "",
    description: "",
    buttonText: "",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
  },
  clientReviews: {
    review1: "",
    clientName1: "",
    review2: "",
    clientName2: "",
    review3: "",
    clientName3: "",
  },
  giftCards: {
    backgroundImage: "",
    description: "",
    buttonText: "",
    title2: "",
    description2: "",
    buttonText2: "",
  },
  section9: {
    title: "",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
  },
  section10: {
    title1: "",
    description: "",
    buttonText: "",
  },
};
